name: brick_bootstrap5_plus
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/onecodemanzh/brick-bootstrap5-plus

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intersperse: ^2.0.0
  intl: ^0.19.0
  tinycolor2: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
