name: brick_bootstrap5_plus
description: A Flutter UI Dart libraries with the bootstrap5.
version: 1.0.0
repository: https://github.com/onecodemanzh/brick-bootstrap5-plus

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-9.2.1
  intersperse: ^2.0.0
  intl: ^0.19.0
  tinycolor2: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
